[package]
name = "arweave-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.132"
serde_json = { version = "1.0.73", features = ["derive"] }
thiserror = "1.0.34"
pretend = "0.3.0"